name       : whois
version    : 5.5.4
release    : 21
source     :
    - https://github.com/rfc1036/whois/archive/v5.5.4.tar.gz : be3f475853c8154cf5dd7ee96060b93dadf5b0d3ee4e16e9c67c5db96f7bd214
license    : GPL-2.0-or-later
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn2)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN2=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
    install -Dm00644 whois.conf $installdir/usr/share/doc/whois/whois.conf
