name       : whois
version    : 5.2.10
release    : 3
source     :
    - https://github.com/rfc1036/whois/archive/v5.2.10.tar.gz : 8169bead001fb68d14f09a49c117d3408d48a3378f3a67eb0e56848a637ad54e
license    : GPL-2.0
summary    : whois client
builddeps  :
    - pkgconfig(libidn)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
