name       : whois
version    : 5.2.14
release    : 6
source     :
    - https://github.com/rfc1036/whois/archive/v5.2.14.tar.gz : b776279b4c6baa41da5ded0b33bbe9be93bf20031fa4dfd8e79784045c4021a1
license    : GPL-2.0
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
