name       : whois
version    : 5.4.3
release    : 18
source     :
    - https://github.com/rfc1036/whois/archive/v5.4.3.tar.gz : 2c2de92407ce925c270246e141234ab6fc6f7894d81b3b8a23e8c80b6a6c334c
license    : GPL-2.0-or-later
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn2)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN2=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
    install -Dm00644 whois.conf $installdir/usr/share/doc/whois/whois.conf
