name       : whois
version    : 5.4.1
release    : 16
source     :
    - https://github.com/rfc1036/whois/archive/v5.4.1.tar.gz : a2db7f69d230054489a282a615c01d86be65a7dbc53a66a390e5c9981c26d131
license    : GPL-2.0-or-later
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn2)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN2=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
    install -Dm 00644 whois.conf $installdir/usr/share/doc/whois/whois.conf
