name       : whois
version    : 5.4.2
release    : 17
source     :
    - https://github.com/rfc1036/whois/archive/v5.4.2.tar.gz : d928b981dc949a2ea1d0512d20da74707953369f889a88d8f84f1a4b05b822d2
license    : GPL-2.0-or-later
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn2)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN2=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
    install -Dm00644 whois.conf $installdir/usr/share/doc/whois/whois.conf
