name       : whois
version    : 5.2.7
release    : 2
source     :
    - https://github.com/rfc1036/whois/archive/v5.2.7_bpo70+1.tar.gz : 80a898de211c6d1c1236d2fe3c017c837425ba4ae083bca1ed4e4bd77f1aacf6
license    : GPL-2.0
summary    : whois client
builddeps  :
    - pkgconfig(libidn)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
