name       : whois
version    : 5.2.15
release    : 7
source     :
    - https://github.com/rfc1036/whois/archive/v5.2.15.tar.gz : f63c467807766e38f4ee50672aa2269bb321af37fda70d9b9456124fb8e24404
license    : GPL-2.0
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn2)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN2=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
