name       : whois
version    : 5.2.12
release    : 5
source     :
    - https://github.com/rfc1036/whois/archive/v5.2.12.tar.gz : 8485aa02909fd6aaa1cfd8b5e63559310879bf8a62793a83c96a4502164b968a
license    : GPL-2.0
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
