name       : whois
version    : 5.5.0
release    : 19
source     :
    - https://github.com/rfc1036/whois/archive/v5.5.0.tar.gz : 0fa2931c4656210794dd2ee3552eccbeb11fe8572dcd1d758cf47208978dd8c1
license    : GPL-2.0-or-later
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn2)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN2=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
    install -Dm00644 whois.conf $installdir/usr/share/doc/whois/whois.conf
