name       : whois
version    : 5.2.11
release    : 4
source     :
    - https://github.com/rfc1036/whois/archive/v5.2.11.tar.gz : baaa9622ce92533af89005776acc6e007be9c9e8d088e34567ce4f955ab65ddf
license    : GPL-2.0
summary    : whois client
builddeps  :
    - pkgconfig(libidn)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
