name       : whois
version    : 5.5.1
release    : 20
source     :
    - https://github.com/rfc1036/whois/archive/v5.5.1.tar.gz : 3877cddb0a9dbbdbd27b6a32b038f6fa0f4ba5df547c542baab1d90853b0668d
license    : GPL-2.0-or-later
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn2)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN2=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
    install -Dm00644 whois.conf $installdir/usr/share/doc/whois/whois.conf
