name       : whois
version    : 5.2.20
release    : 11
source     :
    - http://ftp.debian.org/debian/pool/main/w/whois/whois_5.2.20.tar.xz : 6848ab671750ab3782fe4ab2a47910fe4e25aa93894e4d0f3f67b5fcee06c009
license    : GPL-2.0
component  : network.clients
summary    : whois client
builddeps  :
    - pkgconfig(libidn2)
description: |
    whois client - perform DNS lookups on remote hosts
build      : |
    %make HAVE_LIBIDN2=1 HAVE_ICONV=1
install    : |
    %make_install prefix=/usr BASEDIR="$installdir" install-whois
    install -Dm 00644 whois.conf $installdir/usr/share/doc/whois/whois.conf
